name: Build and test

on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - reopened

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 8

    - name: Setup Node 
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install

    - name: Test build
      run: pnpm run build

    - name: Run tests 
      run: pnpm test
